from enum import Enum


class MechanicalEffectType(Enum):
    ROLL_MODIFIER = "ROLL_MODIFIER"
    REROLL = "REROLL"
    STRIKE_DAMAGE = "STRIKE_DAMAGE"
    RESOURCE_PERMISSION = "RESOURCE_PERMISSION"
    RESOURCE_CONVERSION = "RESOURCE_CONVERSION"
    POST_PREVENTION_EFFECT = (
        "POST_PREVENTION_EFFECT"
    )
    TRIGGERED_EFFECT = "TRIGGERED_EFFECT"